apiVersion: batch/v1
kind: CronJob
metadata:
  name: sipexer
  namespace: kamailio
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: sipexer
              image: ghcr.io/denyspozniak/sipexer:latest
              command: ['./sipexer', 'tcp:kamailio-svc.kamailio.svc.cluster.local:5060']
