apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamailio-3g
  namespace: kamailio-3g
  labels:
    app: kamailio-3g
    tier: voip
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kamailio-3g
  template:
    metadata:
      labels:
        app: kamailio-3g
        tier: voip
    spec:
      containers:
        - name: kamailio-3g
          #image: safarov/kamailio:latest
          command: ["/usr/sbin/kamailio"]
          args: ["-DD", "-E", "-ddd"] 
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - name: sip
              containerPort: 5060
              protocol: TCP
          resources:
            requests:
              memory: 128Mi
              cpu: 128m
            limits:
              memory: 512Mi
              cpu: 500m

