apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kamailio

resources:
- ../base

replicas:
- count: 5
  name: kamailio

#images:
#- name: ghcr.io/kamailio/kamailio:5.8.4-bookworm
#  newTag: latest
