apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamailio
  namespace: kamailio
  labels:
    app: kamailio
    tier: voip
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kamailio
  template:
    metadata:
      labels:
        app: kamailio
        tier: voip
    spec:
      containers:
        - name: kamailio
          image: ghcr.io/kamailio/kamailio:5.8.4-bookworm
          command: ["/usr/sbin/kamailio"]
          args: ["-DD", "-E", "-ddd"] 
          volumeMounts:
            - name: kamailio-config
              mountPath: /etc/kamailio/kamailio.cfg
              subPath: kamailio.cfg
          imagePullPolicy: Always
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - name: sip
              containerPort: 5060
              protocol: TCP
          resources:
            requests:
              memory: 128Mi
              cpu: 128m
            limits:
              memory: 512Mi
              cpu: 500m
      volumes:
        - name: kamailio-config
          configMap:
            name: kamailio-config
            