apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: kamailio-config
    files:
      - ./kamailio.cfg
  - name: kamailio-python3
    files:
      - ./kamailio3.py
