apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - deployment.yaml
  - statefulset.yaml
  - service.yaml

configMapGenerator:
  - files:
      - ./kamailio.cfg
    name: kamailio-config
  - files:
      - ./kamailio3s.py
    name: kamailio-python
