apiVersion: v1
kind: Service
metadata:
  name: kamailio-svc
  namespace: kamailio
spec:
  selector:
    app: kamailio
  ports:
    - name: sip
      port: 5060
      protocol: TCP
      targetPort: 5060
  #type: ClusterIP
  type: LoadBalancer

