apiVersion: v1
kind: Service
metadata:
  name: kamailio-svc
  labels:
    app.kubernetes.io/name: kamailio
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kamailio
  ports:
    - name: sip-udp
      port: 5060
      protocol: UDP
      targetPort: sip-udp
    - name: sip-tcp
      port: 5060
      protocol: TCP
      targetPort: sip-tcp
