apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kamailio
  namespace: kamailio
  labels:
    app: kamailio
    tier: voip
spec:
  serviceName: "kamailio-svc"
  replicas: 2
  selector:
    matchLabels:
      app: kamailio
  template:
    metadata:
      labels:
        app: kamailio
    spec:
      containers:
        - name: kamailio
          image: ghcr.io/kamailio/kamailio:5.8.4-bookworm
          command: ["apt-get update && apt-get install -y sngrep && /usr/sbin/kamailio"]
          args: ["-DD", "-E"] 
          volumeMounts:
            - name: kamailio-config
              mountPath: /etc/kamailio/kamailio.cfg
              subPath: kamailio.cfg
            - name: kamailio-python3s
              mountPath: /etc/kamailio/kamailio3s.py
              subPath: kamailio3s.py
            - name: kamailio-python3
              mountPath: /etc/kamailio/kamailio3.py
              subPath: kamailio3.py

          imagePullPolicy: Always
      volumes:
        - name: kamailio-config
          configMap:
            name: kamailio-config
        - name: kamailio-python3s
          configMap:
            name: kamailio-python3s
        - name: kamailio-python3
          configMap:
            name: kamailio-python3
  